# Generated by Django 5.1.7 on 2025-04-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_newsletter_id_alter_subscriber_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='author',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='sent_at',
        ),
    ]
