# Generated by Django 5.1.7 on 2025-04-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_remove_newsletter_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
