# Generated by Django 5.1.7 on 2025-04-12 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_newsletter_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
