# Generated by Django 5.1.7 on 2025-04-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_emailconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='Active_sub',
            field=models.BooleanField(default=True),
        ),
    ]
