# Generated by Django 5.1.7 on 2025-06-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_usersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='internet_page',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailconfirmation',
            name='profitability',
            field=models.FloatField(default=0.0),
        ),
    ]
